steam_reviews:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      schema: default
      threads: 2
      send_receive_timeout: 14400
      custom_settings:
        final: 1
        join_use_nulls: 1
