repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.2.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['dbt-core>=1.9', 'dbt-clickhouse==1.10.3', 'sqlfluff-templater-dbt==4.2.2']
        files: dbt\/models\/.*\.sql$
